"""
github_agent.py

The GitHub Agent.
Its job is to take the completed knowledge base or study plan
and create a clean, well-structured GitHub repository on the
user's account.

This agent only runs when:
1. The intent is 'guide'
2. The user has explicitly approved repo creation

This is the human-in-the-loop pattern — the agent never
takes real-world action without user consent.

This is the FINAL step in the guide pipeline.
"""

from github import Github, GithubException
from config import GITHUB_USERNAME
import os
import re


# ── Helpers ──────────────────────────────────────────────────────

def slugify(text: str) -> str:
    """
    Converts a query into a clean GitHub repo name.

    Example input:  "Build me a knowledge base on machine learning"
    Example output: "knowledge-base-machine-learning"

    Example input:  "Create a study plan for learning Python"
    Example output: "knowledge-base-learning-python"
    """
    slug = text.lower().strip()

    # Remove common filler phrases so repo name stays clean
    filler = [
        "build me a knowledge base on",
        "build a knowledge base on",
        "create a knowledge base on",
        "create a knowledge base for",
        "knowledge base on",
        "knowledge base for",
        "create a study plan for",
        "create a study plan on",
        "study plan for",
        "study plan on",
        "create a learning guide for",
        "create a learning guide on",
        "create a guide for",
        "create a guide on",
        "learning guide for",
        "learning guide on",
        "a guide to",
        "a guide for",
        "guide for",
        "guide to",
        "create a",
        "create",
        "build me",
        "build a",
    ]

    for phrase in filler:
        slug = slug.replace(phrase, "")

    # Remove special characters except spaces and hyphens
    slug = re.sub(r"[^a-z0-9\s-]", "", slug)

    # Replace spaces with hyphens
    slug = slug.strip().replace(" ", "-")

    # Collapse multiple hyphens into one
    slug = re.sub(r"-+", "-", slug)

    # Keep it short and readable
    slug = slug[:60].strip("-")

    return f"knowledge-base-{slug}"


def build_readme(query: str, report: str, sources: list) -> str:
    """
    Builds a polished README.md for the knowledge base repo.
    The report content is embedded directly as the main body.
    """
    # Clean up the title
    title = query.strip().title()

    source_links = "\n".join([
        f"- [{s['title']}]({s['url']})"
        for s in sources
    ])

    return f"""# {title}

![Generated by AI](https://img.shields.io/badge/Generated%20by-AI%20Agent-blue)
![Sources](https://img.shields.io/badge/Sources-{len(sources)}-green)
![Pipeline](https://img.shields.io/badge/Pipeline-LangGraph-purple)

> This knowledge base was autonomously generated by a multi-agent AI pipeline
> built with LangGraph, FastAPI, and React.
> [View the project →](https://github.com/{GITHUB_USERNAME}/research-agent)

---

{report}

---

## Sources

{source_links}

---

*Generated by [research-agent](https://github.com/{GITHUB_USERNAME}/research-agent)*
"""


# ── Main Agent Function ──────────────────────────────────────────

def github_agent(
    query: str,
    report: str,
    summary: str,
    fact_check: str,
    sources: list,
) -> dict:
    """
    Creates a GitHub repository containing the knowledge base.

    Takes all outputs from previous agents.
    Returns a dict with the repo URL.

    Example input:  query="knowledge base on ML", report="...", ...
    Example output: {"agent": "github", "status": "done", "repo_url": "https://github.com/..."}
    """
    print("🐙 GitHub Agent creating repository...")

    # Initialise GitHub client inside the function
    # so it only connects when actually called
    g = Github(os.getenv("GITHUB_TOKEN"))
    user = g.get_user()

    # Build clean repo name from query
    repo_name = slugify(query)

    try:
        # Create the public repository
        repo = user.create_repo(
            name=repo_name,
            description=f"AI-generated knowledge base: {query}",
            private=False,
            auto_init=False
        )

        print(f"✅ Repository created: {repo.html_url}")

        # Single clean README — the knowledge base itself
        repo.create_file(
            "README.md",
            "feat: add AI generated knowledge base",
            build_readme(query, report, sources)
        )

        return {
            "agent": "github",
            "status": "done",
            "repo_url": repo.html_url,
            "repo_name": repo_name
        }

    except GithubException as e:
        print(f"❌ GitHub error: {e}")
        return {
            "agent": "github",
            "status": "error",
            "repo_url": "",
            "repo_name": repo_name,
            "error": str(e)
        }